#!/bin/bash
exec $HOME/android-ndk-r15c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-g++ \
    --sysroot=$HOME/android-ndk-r15c/platforms/android-24/arch-arm64 \
    -I$HOME/android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/include \
    -I$HOME/android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/include \
    "$@"
